server:
  port: 8070

spring:
  application:
    name: ncov
  rabbitmq:
    host: 118.195.156.48
    port: 5672
    username: admin
    password: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.195.156.48:3306/ncov?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: ncov
    password: Wsymt.1203
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      test-on-borrow: true
      validationQuery: SELECT 1
      stat-view-servlet:
        enabled: false
  aop:
    auto: true
    proxy-target-class: true
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    port: 6379
    host: 118.195.156.48
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: PT30M
    database: 0

  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: site.ncov.www.ncov.**.model.vo
  global-config:
    db-config:
      logic-delete-field: is_delete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    cache-enabled: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

# LOGGING
logging:
  config: classpath:logback.xml



